import type { EditorColor, ColorPalette } from "../types";

export const colors: ColorPalette = {
  primary: "#FFCB93",
  secondary: "#D4A574",
  tertiary: "#B58156",
  intermediate: "#6B5B4F",
  black: "#1D1B19",
  blue: "#74AA90",
  green: "#ACB452",
  orange: "#D5712F",
  purple: "#AD74EE",
  red: "#F75123",
  white: "#C9B19F",
  yellow: "#D29834",
  brightBlue: "#87CBAB",
  brightGreen: "#D3DD62",
  brightOrange: "#F59D50",
  brightPurple: "#C39BD3",
  brightRed: "#FF7979",
  brightYellow: "#F5AF36",
};

export const colorMapping: EditorColor = {
  ...colors,
  background: colors.black,
  foreground: colors.white,
  accentPrimary: colors.primary,
  accentSecondary: colors.secondary,
  accentTertiary: colors.tertiary,
  keyword: colors.red,
  variable: colors.primary,
  number: colors.brightPurple,
  boolean: colors.brightPurple,
  nullable: colors.brightRed,
  string: colors.green,
  function: colors.blue,
  comment: colors.intermediate,
  punctuation: colors.tertiary,
  type: colors.brightOrange,
  typeAnnotation: colors.orange,
};
