import type { EditorColor, ColorPalette } from "../types";

export const colors: ColorPalette = {
  primary: "#FFCB93",
  secondary: "#D4A574",
  tertiary: "#B58156",
  intermediate: "#6B5B4F",
  black: "#1D1B19",
  blue: "#74AA90",
  blueBright: "#87CBAB",
  green: "#ACB452",
  greenBright: "#D3DD62",
  orange: "#D5712F",
  orangeBright: "#F59D50",
  purple: "#AD74EE",
  purpleBright: "#C39BD3",
  red: "#F75123",
  redBright: "#FF7979",
  white: "#C9B19F",
  yellowBright: "#F5AF36",
  yellow: "#D29834",
};

export const colorMapping: EditorColor = {
  ...colors,
  background: colors.black,
  foreground: colors.white,
  accentPrimary: colors.primary,
  accentSecondary: colors.secondary,
  accentTertiary: colors.tertiary,
  keyword: colors.red,
  variable: colors.primary,
  number: colors.purpleBright,
  boolean: colors.purpleBright,
  nullable: colors.redBright,
  string: colors.green,
  function: colors.blue,
  comment: colors.intermediate,
  punctuation: colors.tertiary,
  type: colors.orangeBright,
  typeAnnotation: colors.orange,
};
